services:
  web:
    container_name: web
    build: ./main
    ports:
      - "5016:5016"
    links:
      - redis
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
    volumes:
      - ./main:/app

  redis:
    container_name: redis
    image: redis/redis-stack
    hostname: redis

  worker:
    build:
      context: ./main
    hostname: worker
    entrypoint: celery
    command: -A app.celery worker --loglevel=info
    volumes:
      - ./main:/app
    links:
      - redis
    depends_on:
      - redis

  nuclei:
    container_name: nuclei
    build: ./nuclei
    ports:
      - "8091:8091"
    links:
      - web
    depends_on:
      - web
    environment:
      - FLASK_ENV=development
    volumes:
      - /root/nuclei-templates:/templates
      - ./report:/report

  nmap:
    container_name: nmap
    build: ./nmap
    ports:
      - "8092:8092"
    links:
      - web
    depends_on:
      - web
    environment:
      - FLASK_ENV=development
    volumes:
      - ./report:/report

  wpscan:
    container_name: wpscan
    build: ./wpscan
    ports:
      - "8093:8093"
    links:
      - web
    depends_on:
      - web
    environment:
      - FLASK_ENV=development
    volumes:
      - ./root/:/report