name: parspack

networks:
  engine_network:
    driver: bridge

services:
  main_web:
    build:
      context: ./main
    hostname: main
    ports:
      - "5016:5016"
    command: gunicorn -w 4 -k gevent app:app -b 0.0.0.0:5016
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./main/results:/app/results
    networks:
      - engine_network

  main_redis:
    container_name: main_redis
    image: redis/redis-stack
    hostname: main_redis
    environment:
      - REDIS_ARGS="--requirepass mypassword"
    networks:
      - engine_network

  main_worker:
    build:
      context: ./main
    hostname: worker
    entrypoint: celery
    command: -A app.celery worker --loglevel=info
    volumes:
      - ./main/results:/app/reports
    networks:
      - engine_network

  nmap:
    build:
      context: ./nmap
      dockerfile: Dockerfile
    hostname: nmap
    ports:
      - "8091:8091"
    volumes:
      - ./main/results:/app/reports
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - engine_network

  nuclei:
    build:
      context: ./nuclei
      dockerfile: Dockerfile
    hostname: nuclei
    ports:
      - "8092:8092"
    volumes:
      - ./main/results:/app/reports
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - engine_network

  wpscan:
    build:
      context: ./wpscan
      dockerfile: Dockerfile
    hostname: wpscan
    ports:
      - "8093:8093"
    volumes:
      - ./main/results:/app/reports
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - engine_network
