name: nuclei
services:
  nuclei_api:
    build:
      context: .
    command: gunicorn -w 4 -k gevent app:app -b 0.0.0.0:8091
    ports:
      - "8091:8091"
    depends_on:
      - nuclei_redis
      - nuclei_celery
    volumes:
      - ./reports:/reports

  nuclei_celery:
    build:
      context: .
    command: celery -A nuclei_tasks worker --loglevel=info -P eventlet
    depends_on:
      - nuclei_redis
    volumes:
      - ./reports:/reports

  nuclei_redis:
    image: "redis"
