name: nuclei
services:
  fastapi-nuclei:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8092:8092"  # Map container port 8092 to host port 8092
    volumes:
      - ./reports:/app/reports  # Mount the reports folder for persistent storage
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is displayed in Docker logs
