name: nmap
services:
  nmap_api:
    build:
      context: .
    command: gunicorn -w 4 -k gevent app:app -b 0.0.0.0:8092
    ports:
      - "8092:8092"
    depends_on:
      - nmap_redis
      - nmap_celery
    volumes:
      - ./reports:/reports

  nmap_celery:
    build:
      context: .
    command: celery -A nmap_tasks worker --loglevel=info -P eventlet
    depends_on:
      - nmap_redis
    volumes:
      - ./reports:/reports

  nmap_redis:
    image: redis
