name: nmap
services:
  fastapi-nmap:
    build:
      context: .  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "8091:8091"  # Map container port 8091 to host port 8091
    volumes:
      - ./reports:/app/reports  # Mount the reports folder for persistent storage
    environment:
      - PYTHONUNBUFFERED=1  # Ensure Python output is displayed in Docker logs
