name: wpscan
services:
  wpscan_api:
    build:
      context: .
    command: gunicorn -w 4 -k gevent app:app -b 0.0.0.0:8093
    ports:
      - "8093:8093"
    depends_on:
      - wpscan_redis
      - wpscan_celery
    volumes:
      - ./reports:/reports

  wpscan_celery:
    build:
      context: .
    command: celery -A wpscan_tasks worker --loglevel=info -P eventlet
    depends_on:
      - wpscan_redis
    volumes:
      - ./reports:/reports

  wpscan_redis:
    image: redis
